name: SMT220 Kernel Build
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 2.7 (Conda)
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 2.7

      - name: Install Build Tools
        run: |
          sudo apt-get update
          # Gerekli tüm araçları ve derleyiciyi en baştan kuruyoruz
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm gcc-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          mkdir -p out
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Config oluştur
          make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- gta7litewifi_defconfig
          
          # Derleme (Zırhlı Komut):
          # KCFLAGS="-w" -> Uyarıları gizler
          # -fno-stack-protector -> Modern güvenlik hatalarını engeller
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KCFLAGS="-w -fno-stack-protector"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: SMT220-Kernel
          path: out/arch/arm64/boot/
